server:
  port: 8000

web:
  domain: http://localhost

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/doubao?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&AllowPublicKeyRetrieval=True
    type: com.zaxxer.hikari.HikariDataSource
  redis:
    database: 11
    host: 127.0.0.1
    port: 6379
#    timeout: 6000ms
#    password:
#    cluster:
#      max-redirects: 1
#      nodes:
#        - 10.98.66.65:6379
#        - 10.98.66.66:6379
#        - 10.98.66.67:6379

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: com.douyuehan.doubao.model.entity


logging:
  level:
    root: info
    com.douyuehan.doubao: debug